### ISSUE TITLE
Support for ohm 2.0.0

### ISSUE THREAD

**Issue by hrkeni** [DatabaseCleaner/database_cleaner-ohm#1]
Ohm's new release uses a new gem called 'redic'. The current cleaner doesn't work with this.

**Comment by bmabey** [comment]
This won't be added unless a pull request is provided.

**Comment by hrkeni** [comment]
I've added the functionality and created a pull request
https://github.com/bmabey/database_cleaner/pull/277

**Comment by etagwerker** [comment]
This project is no longer maintained. If you really want to bring it back online, please submit an issue here: https://github.com/DatabaseCleaner/database_cleaner/issues
